@base = http://localhost:3333 
@token = 8a987a49

#List
GET http://localhost:3333/ongs

###

# Insert
POST {{base}}/ongs
Content-Type: application/json

{
    "name": "PETLOVE",
    "email": "petlov@gmail.com",
    "whatsapp": "1194002-8922",
    "city":"diadema",
    "uf":"SP"
}

### 

#Send Incidents
POST {{base}}/incidents
Content-Type: application/json
Authorization: {{token}}

{
    "title": "caso 1",
    "description": "Lorem ipsun door",
    "value": 120
}

###
GET {{base}}/incidents

###

#Delete Incidents
DELETE {{base}}/incidents/1
Content-Type: application/json
Authorization: {{token}}